import 'package:flutter/material.dart';
import 'package:flutter_complete_guide/screens/hcsProductsSearchResults_screen.dart';


// Class to handle the UI subcomponent for a specific recipe's ingredient

class IngredientItem extends StatelessWidget {
  final dynamic ingredient;

  IngredientItem(this.ingredient);

  static String checkKeywords(String query) {
    List<String> keywords = [
      'fish',
      'chicken',
      'salt',
      'sugar',
      'butter',
      'eggs',
      'garlic',
      'water',
      'olive oil',
      'milk',
      'flour',
      'onion',
      'pepper',
      'onions',
      'black pepper',
      'brown sugar',
      'egg',
      'cinnamon',
      'all-purpose flour',
      'baking powder',
      'lemon juice',
      'tomatoes',
      'vanilla',
      'vanilla extract',
      'parsley',
      'unsalted butter',
      'baking soda',
      'sour cream',
      'vegetable oil',
      'celery',
      'ginger',
      'lemon',
      'cream cheese',
      'carrots',
      'cheddar cheese',
      'beef',
      'potatoes',
      'oil',
      'honey',
      'nutmeg',
      'cheese',
      'soy sauce',
      'mayonnaise',
      'chicken broth',
      'oregano',
      'cumin',
      'thyme',
      'garlic',
      'pepper',
      'mushrooms',
      'cilantro',
      'basil',
      'pecans',
      'bacon',
      'heavy cream',
      'chicken breasts',
      'worcestershire sauce',
      'paprika',
      'chocolate',
      'chicken',
      'walnuts',
      'chilli',
      'almonds',
      'juice',
      'parmesan cheese',
      'pineapple',
      'rice',
      'orange juice',
      'white sugar',
      'green pepper',
      'raisins',
      'coconut',
      'nuts',
      'dijon mustard',
      'cornstarch',
      'mozarella cheese',
      'buttermilk',
      'vinegar',
      'apples',
      'red pepper',
      'tomato sauce',
      'bread crumbs',
      'oats',
      'spinach',
      'shallots',
      'tomato paste',
      'red bell pepper',
      'lime',
      'shrimp',
      'zucchini',
      'strawberries',
      'rosemary',
      'canola oil',
      'green onions',
      'bananas',
      'scallions',
      'cloves',
      'mustard',
      'cocoa powder',
      'chicken stock',
      'sea salt',
      'chives',
      'whipping cream',
      'bread',
      'maple syrup',
      'orange',
      'corn starch',
      'balsamic vinegar',
      'dry white wine',
      'coriander',
      'bay leaf',
      'ketchup',
      'yogurt',
      'red wine vinegar',
      'avocado',
      'sesame oil',
      'cabbage',
      'bay leaves',
      'chocolate chips',
      'broccoli',
      'salt and black pepper',
      'chicken breast',
      'cocoa',
      'carrot',
      'basil leaves',
      'onion powder',
      'cucumber',
      'peanut butter',
      'allspice',
      'dry mustard',
      'cranberries',
      'mint',
      'ham',
      'green bell pepper',
      'blueberries',
      'soda',
      'wheat flour',
      'peas',
      'curry powder',
      'corn',
      'coconut milk',
      'lettuce',
      'sesame seeds',
      'pork',
      'turmeric',
      'pasta',
      'dill',
      'yellow onion',
      'white wine',
      'red onion',
      'jalapeno chilies',
      'cream of mushroom soup',
      'beans',
      'almond extract',
      'black beans',
      'garlic salt',
      'peanuts',
      'cider vinegar',
      'white vinegar',
      'margarine',
      'green beans',
      'cream',
      'molasses',
      'confectioners sugar',
      'pumpkin',
      'coconut oil',
      'sauce',
      'turkey',
      'yeast',
      'olives',
      'corn syrup',
      'sage',
      'rice vinegar',
      'raspberries',
      'beef broth',
      'salt & pepper',
      'ricotta cheese',
      'salsa',
      'tomato',
      'breadcrumbs',
      'spray',
      'cilantro leaves',
      'parsley leaves',
      'apple cider vinegar',
      'capers',
      'bell pepper',
      'gelatin',
      'green chilies',
      'black olives',
      'feta cheese',
      'swiss cheese',
      'cherry tomatoes',
      'potato',
      'oranges',
      'cool whip',
      'cream of tartar',
      'cornmeal',
      'pineapple juice',
      'italian seasoning',
      'salmon',
      'cooking oil',
    ];

    var words = query.split(' ');
    print(words);
    for (int i = 0; i < keywords.length; i++) {
      for (int j = 0; j < words.length; j++) {
        if (words[j].toLowerCase().contains(keywords[i])) {
          print(words[j]);
          print(keywords[i]);
          return keywords[i];
        }
      }
    }
    print('failed');
    return query;
  }

  @override
  Widget build(BuildContext context) {
    return ListTile(
        tileColor: Color.fromRGBO(255, 255, 255, 1),
        title: Text(ingredient),
        onTap: () {
          Scaffold.of(context).showSnackBar(
            SnackBar(
              //a snackbar is just a material design object which is shown at the bottom of the screen
              content: Text(
                'Searching $ingredient!',
              ),
              duration: Duration(seconds: 1),
            ),
          );
          Future.delayed(Duration(seconds: 1), () {
            var result = checkKeywords(ingredient);
            Navigator.of(context).pushNamed(
                HcsProductsSearchResultsScreen.routeName,
                arguments: result);
          });
        });
  }
}
